version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
      - ./config.yaml:/qdrant/config/config.yaml  # Mount the config file

volumes:
  qdrant_storage:
    driver: local

